"""Generate docs/RULES.md (every design rule: what, why, how to fix, severity, whether it can be
waived) from the rule registry. A test fails if the committed file is stale.
Usage: python -m tools.gen_rule_docs"""

from pathlib import Path

from harness_tool.core.drc import RULES

TARGET = Path(__file__).resolve().parents[1] / "docs" / "RULES.md"

LOGICAL = [
    (
        "cross-strap",
        "warning",
        "A nominal unit is connected to a redundant one.",
        "One failure could affect both chains.",
        "Connect to a redundant copy, or waive with a reason.",
    ),
    (
        "no-connector",
        "info",
        "An interface has no connector chosen on an end.",
        "Without connectors it cannot become wires.",
        "Choose connectors (automatic fix available).",
    ),
    (
        "unconfirmed",
        "info",
        "Connectors were chosen by the tool and not confirmed.",
        "Nobody should assume auto-filled choices were reviewed.",
        "Confirm them (fix available).",
    ),
    (
        "isolated",
        "info",
        "A unit has no interfaces.",
        "It will not appear in any harness.",
        "Connect it, or ignore.",
    ),
]


def render() -> str:
    lines = [
        "# Design rules",
        "",
        "Generated by `python -m tools.gen_rule_docs` from the rule registry; do not edit by hand.",
        "Errors cannot be waived; warnings can be waived with a reason of at least 10 characters.",
        "Rules that need numbers from your standards (see PLACEHOLDERS.md) check nothing until those are filled in, and the rule `unchecked-config` says so.",
        "",
        "## Design rules (background check)",
        "",
        "| Rule | Severity | Topic | Why it matters | How to fix |",
        "| --- | --- | --- | --- | --- |",
    ]
    for r in RULES:
        waive = "waivable" if r.can_waive else "not waivable"
        lines.append(f"| `{r.id}` | {r.severity} ({waive}) | {r.topic} | {r.why} | {r.how} |")
    lines += [
        "",
        "## Logical rules (instant, in the editor)",
        "",
        "| Rule | Severity | What | Why | How to fix |",
        "| --- | --- | --- | --- | --- |",
    ]
    lines += [f"| `{a}` | {b} | {c} | {d} | {e} |" for a, b, c, d, e in LOGICAL]
    lines += [
        "",
        "## Also reported as errors",
        "",
        "Mismatches found by the independent verifier (`verify-mismatch`): a wire missing, extra, swapped or duplicated compared with the interfaces. Fix: regenerate the harnesses.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    TARGET.write_text(render())
    print(f"wrote {TARGET}")


if __name__ == "__main__":
    main()
